version: '3.9'  # Specify the docker-compose file format version

services:
  python-dev:
    image: python:latest  # change 'latest' to specific version
    container_name: python_dev_container
    volumes:
      - .:/src  # Mount the current directory on the host to /src in the container
    working_dir: /src  # Set the working directory inside the container
    tty: true  # Keep the container running with an interactive terminal
    stdin_open: true  # Allow interactive input
    command: bash -c "pip install -r requirements.txt || true && tail -f /dev/null"
    environment:
      - PYTHONUNBUFFERED=1  # Ensure real-time logging of Python scripts
